image: c33s/php:7.4

stages:
    - test

variables:
    COMPOSER_ALLOW_SUPERUSER:       '1'
    COMPOSER_HOME:                  'var/composer'
    COMPOSER_NO_INTERACTION:        '1'
    SYMFONY_DEPRECATIONS_HELPER:    'weak'
    TIMEZONE:                       'Europe/Vienna'
    DEBIAN_FRONTEND:                'noninteractive'
    PHP_XDEBUG_EXTENSION_PATH:      'xdebug.so'

cache:
    #key: "$CI_BUILD_NAME___$CI_BUILD_REF_NAME"
    paths:
        - $COMPOSER_HOME
        - vendor/
        - .robo/bin
        - .robo/cache
        - .robo/vendor

before_script:
    - pwd
    - ls -lsa

####################################################################################################
# _____         _
#|_   _|__  ___| |_
#  | |/ _ \/ __| __|
#  | |  __/\__ \ |_
#  |_|\___||___/\__|
####################################################################################################
test_matrix:
    parallel:
        matrix:
            - SYMFONY_VERSION:
                - '~4.4.0'
                - '~5.2.0'
              PHP_VERSION:
                - '7.4'
    stage: test
    image: "c33s/php:$PHP_VERSION"
    script:
        - 'sed -i "s/\"require\": \"^4.4\"/\"require\": \"$SYMFONY_VERSION\"/" composer.json'
        - tail composer.json -n 7
        - robo init
        - robo test

    coverage: '/^\s*Lines:\s*\d+.\d+\%/'
    artifacts:
        when: always
        paths:
            - tests/_output/

####################################################################################################
#  ____ _               _
# / ___| |__   ___  ___| | __
#| |   | '_ \ / _ \/ __| |/ /
#| |___| | | |  __/ (__|   <
# \____|_| |_|\___|\___|_|\_\
####################################################################################################
check:
    stage: test
    script:
        #- rm -rf $CI_PROJECT_DIR/.ci
        - robo init
        - robo check
