image: endava/php:8.2.15

stages:
  - test

variables:
  COMPOSER_HOME: .composer
  COMPOSER_NO_INTERACTION: '1'
  SYMFONY_DEPRECATIONS_HELPER: 'weak'

  PHP_MEMORY_LIMIT: 1024M
  PHP_XDEBUG_MODE: 'on'
  PHP_XDEBUG_EXTENSION_PATH: 'xdebug.so'

.caches:
  composer:
    - key: composer-$CI_DEFAULT_BRANCH
      when: always
      paths:
        - $COMPOSER_HOME/cache
        - vendor/

  php-cs-fixer:
    - key: php-cs-fixer-$CI_DEFAULT_BRANCH
      fallback_keys:
        - php-cs-fixer-default
      paths:
        - .robo/cache/.php-cs-fixer.cache

  rector:
    - key: rector-$CI_DEFAULT_BRANCH
      paths:
        - .robo/cache/rector

  robo:
    - key: robo-$CI_DEFAULT_BRANCH
      when: always
      paths:
        - .robo/bin
        - .robo/vendor


before_script:
  - mkdir -p .robo/bin/
  - if [[ ! -f .robo/bin/robo.phar ]]; then wget https://github.com/consolidation/robo/releases/download/4.0.4/robo.phar -O .robo/bin/robo.phar; fi

####################################################################################################
# _____         _
#|_   _|__  ___| |_
#  | |/ _ \/ __| __|
#  | |  __/\__ \ |_
#  |_|\___||___/\__|
####################################################################################################
test_matrix:
  stage: test
  parallel:
    matrix:
      - SYMFONY_VERSION:
          - '~6.0.0'
          - '~6.4.0'
        PHP_VERSION:
          - '8.2.15'
          - '8.3.2'
  image: "endava/php:$PHP_VERSION"

  coverage: '/^\s*Lines:\s*\d+.\d+\%/'
  cache:
    - !reference [ .caches, composer ]
    - !reference [ .caches, robo ]

  script:
    - 'sed -i "s/\"require\": \"^6.4\"/\"require\": \"$SYMFONY_VERSION\"/" composer.json'
    - tail composer.json -n 7
    - php .robo/bin/robo.phar init
    - php .robo/bin/robo.phar test

  artifacts:
    when: always
    paths:
      - tests/_output/

####################################################################################################
#  ____ _               _
# / ___| |__   ___  ___| | __
#| |   | '_ \ / _ \/ __| |/ /
#| |___| | | |  __/ (__|   <
# \____|_| |_|\___|\___|_|\_\
####################################################################################################
check:
  stage: test
  script:
    - php .robo/bin/robo.phar init
    - php .robo/bin/robo.phar check

  cache:
    - !reference [ .caches, composer ]
    - !reference [ .caches, php-cs-fixer ]
    - !reference [ .caches, rector ]
    - !reference [ .caches, robo ]
