build:
    dependencies:
        before:
            - 'wget https://github.com/consolidation/robo/releases/download/4.0.4/robo.phar'
            -
                command: 'php robo.phar init --no-interaction'
                environment:
                    COMPOSER_ALLOW_SUPERUSER: 1
                    COMPOSER_NO_INTERACTION: 1
                    SYMFONY_DEPRECATIONS_HELPER: weak
                    TIMEZONE: Europe/Vienna
    tests:
        before:
            -
                command: 'php robo.phar test --no-interaction'
                coverage:
                    file: 'tests/_output/coverage.xml'
                    format: 'clover'

checks:
    php:
        code_rating: true
        duplication: true

filter:
    paths:
        - 'src/*'
    excluded_paths: []
