<?php  //[STAMP] 39f75c00ea824b73c7d3763e76c7caa8
// phpcs:ignoreFile
namespace Tests\Support\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build

trait UnitTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     *
     * @see \Tests\Support\Helper\Unit::getPageFixtureDir()
     */
    public function getPageFixtureDir() {
        return $this->getScenario()->runStep(new \Codeception\Step\Action('getPageFixtureDir', func_get_args()));
    }
}
